version: '2'
services:
    ldap:
        build:
            context: ./tasks/docker/ldap
        volumes:
            - "./tasks/files/ldap/openldap:/etc/openldap"
#        command: /usr/bin/bash
        command: bash -c "/usr/bin/slapd -u ldap -g ldap -h 'ldaps:///' && killall slapd && slaptest -f /etc/openldap/slapd.conf -F /var/lib/openldap/slapd.d/ && chown -R ldap:ldap /var/lib/openldap/slapd.d && /usr/bin/slapd -u ldap -g ldap -h 'ldaps:///' -F '/var/lib/openldap/slapd.d' && ldapadd -D 'cn=root,dc=hashru,dc=nl' -f /etc/openldap/hashru.nl.ldif -w 'hashru' -x && bash"
