version: '2'
services:
    ldap:
        build:
            context: ./tasks/docker/ldap
        volumes:
            - "./tasks/files/ldap/slapd.conf:/etc/openldap/slapd.conf"
            - "./tasks/files/ldap/hashru.nl.ldif:/etc/openldap/hashru.nl.ldif"
        command: bash
#        command: /usr/bin/slapd -u ldap -g ldap -d255
